#!/usr/bin/env python3
"""Sync skills/<category>/<skill-name>/ into a single bundled plugin at
plugins/<PLUGIN_NAME>/, regenerate .claude-plugin/marketplace.json to list
it, and refresh the skills table in README.md.

skills/ is the source of truth: this is where you write and edit skills,
organized by category for humans browsing the repo. plugins/,
.claude-plugin/marketplace.json, and the README's skills table are build
output - never hand-edit them, re-run this script instead after adding,
renaming, or editing a skill.

Every skill is bundled into one plugin (PLUGIN_NAME below) rather than
published as its own plugin, so installing once gets every skill and every
skill's slash command reads /<PLUGIN_NAME>:<skill-name> - not
/<skill-name>:<skill-name>, which is what one-plugin-per-skill produces. A
Claude Code plugin needs each skill under exactly
<plugin-root>/skills/<skill-name>/SKILL.md (one level, no custom path
override exists for skills unlike commands/agents/hooks), so a two-level
skills/<category>/<skill-name>/ tree cannot be a marketplace source
directly - hence this sync step.

Usage: python3 scripts/sync_plugins.py
"""
from __future__ import annotations

import json
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = REPO_ROOT / "skills"
PLUGINS_DIR = REPO_ROOT / "plugins"
MARKETPLACE_PATH = REPO_ROOT / ".claude-plugin" / "marketplace.json"
README_PATH = REPO_ROOT / "README.md"

README_TABLE_START = "<!-- SKILLS_TABLE:START - generated by scripts/sync_plugins.py, do not edit by hand -->"
README_TABLE_END = "<!-- SKILLS_TABLE:END -->"

# Categories under skills/ that are real folder organization but should
# never be published as installable plugins.
EXCLUDED_CATEGORIES = {"deprecated", "in-progress"}

MARKETPLACE_NAME = "anotherbuginthecode"
MARKETPLACE_DESCRIPTION = "Alessandro Mangone's personal Claude Code skills marketplace."
MARKETPLACE_OWNER = {"name": "Alessandro Mangone", "email": "alessandromangone.dev@gmail.com"}

# The single plugin every skill is bundled into. Its name is also the
# slash-command prefix (/<PLUGIN_NAME>:<skill-name>), so changing it changes
# every installed skill's command.
PLUGIN_NAME = "anotherbuginthecode-skills"
PLUGIN_DESCRIPTION = "All of Alessandro Mangone's Claude Code skills, bundled into one plugin. See the skills table below for what each one does."


def parse_frontmatter(skill_md: Path) -> dict:
    text = skill_md.read_text(encoding="utf-8")
    match = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    if not match:
        raise ValueError(f"{skill_md} has no YAML frontmatter")
    frontmatter: dict[str, str] = {}
    for line in match.group(1).splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        frontmatter[key.strip()] = value
    return frontmatter


def find_skills() -> list[tuple[str, str, Path]]:
    """Returns (category, skill_name, skill_dir) for every publishable
    skills/<category>/<skill_name>/SKILL.md, skipping EXCLUDED_CATEGORIES."""
    found = []
    for skill_md in sorted(SKILLS_DIR.glob("*/*/SKILL.md")):
        skill_dir = skill_md.parent
        category = skill_dir.parent.name
        skill_name = skill_dir.name
        if category in EXCLUDED_CATEGORIES:
            continue
        found.append((category, skill_name, skill_dir))
    return found


def build_hint(frontmatter: dict, skill_name: str) -> str:
    """How a human would actually invoke this skill, for the README table."""
    if frontmatter.get("user-invocable", "").lower() == "true":
        arg_hint = frontmatter.get("argument-hint", "").strip()
        command = f"/{PLUGIN_NAME}:{skill_name}"
        return f"`{command} {arg_hint}`" if arg_hint else f"`{command}`"
    return "Triggers automatically when your request matches its description"


def copy_skill(plugin_dir: Path, category: str, skill_name: str, skill_dir: Path) -> dict:
    dest_skill_dir = plugin_dir / "skills" / skill_name
    shutil.copytree(skill_dir, dest_skill_dir)

    frontmatter = parse_frontmatter(skill_dir / "SKILL.md")
    description = frontmatter.get("description", "")

    return {
        "name": skill_name,
        "description": description,
        "category": category,
        "hint": build_hint(frontmatter, skill_name),
    }


def render_readme_table(skill_entries: list[dict]) -> str:
    by_category: dict[str, list[dict]] = {}
    for entry in skill_entries:
        by_category.setdefault(entry["category"], []).append(entry)

    lines: list[str] = []
    for category in sorted(by_category):
        lines.append(f"### {category.capitalize()}")
        lines.append("")
        lines.append("| Skill | Description | How to use |")
        lines.append("| --- | --- | --- |")
        for entry in sorted(by_category[category], key=lambda e: e["name"]):
            description = entry["description"].replace("|", "\\|").replace("\n", " ")
            hint = entry["hint"].replace("|", "\\|")
            lines.append(f"| `{entry['name']}` | {description} | {hint} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def update_readme(skill_entries: list[dict]) -> None:
    if not README_PATH.exists():
        print(f"{README_PATH.name} does not exist, skipping README update", file=sys.stderr)
        return
    text = README_PATH.read_text(encoding="utf-8")
    if README_TABLE_START not in text or README_TABLE_END not in text:
        print(
            f"{README_PATH.name} is missing the SKILLS_TABLE markers, skipping README update",
            file=sys.stderr,
        )
        return

    before, rest = text.split(README_TABLE_START, 1)
    _, after = rest.split(README_TABLE_END, 1)
    table = render_readme_table(skill_entries)
    new_text = f"{before}{README_TABLE_START}\n\n{table}\n{README_TABLE_END}{after}"
    README_PATH.write_text(new_text, encoding="utf-8")


def main() -> None:
    skills = find_skills()
    if not skills:
        print("No publishable skills found under skills/*/*/SKILL.md", file=sys.stderr)
        sys.exit(1)

    seen_names: set[str] = set()
    for _, skill_name, _ in skills:
        if skill_name in seen_names:
            print(f"Duplicate skill name across categories: {skill_name}", file=sys.stderr)
            sys.exit(1)
        seen_names.add(skill_name)

    # plugins/ is fully derived from skills/ - wipe and rebuild rather than
    # patch, so a renamed or removed skill can never leave a stale plugin
    # behind.
    if PLUGINS_DIR.exists():
        shutil.rmtree(PLUGINS_DIR)
    plugin_dir = PLUGINS_DIR / PLUGIN_NAME
    plugin_dir.mkdir(parents=True)

    skill_entries = [
        copy_skill(plugin_dir, category, skill_name, skill_dir)
        for category, skill_name, skill_dir in skills
    ]

    plugin_json = {
        "name": PLUGIN_NAME,
        "description": PLUGIN_DESCRIPTION,
        "version": "0.1.0",
    }
    claude_plugin_dir = plugin_dir / ".claude-plugin"
    claude_plugin_dir.mkdir(parents=True, exist_ok=True)
    (claude_plugin_dir / "plugin.json").write_text(
        json.dumps(plugin_json, indent=2) + "\n", encoding="utf-8"
    )

    marketplace = {
        "$schema": "https://anthropic.com/claude-code/marketplace.schema.json",
        "name": MARKETPLACE_NAME,
        "description": MARKETPLACE_DESCRIPTION,
        "owner": MARKETPLACE_OWNER,
        "plugins": [
            {
                "name": PLUGIN_NAME,
                "description": PLUGIN_DESCRIPTION,
                "source": f"./plugins/{PLUGIN_NAME}",
            }
        ],
    }
    MARKETPLACE_PATH.parent.mkdir(parents=True, exist_ok=True)
    MARKETPLACE_PATH.write_text(json.dumps(marketplace, indent=2) + "\n", encoding="utf-8")

    update_readme(skill_entries)

    print(f"Synced {len(skill_entries)} skill(s) into {plugin_dir.relative_to(REPO_ROOT)}/skills/")
    for entry in skill_entries:
        print(f"  - {entry['name']} ({entry['category']})")
    print(f"Regenerated {MARKETPLACE_PATH.relative_to(REPO_ROOT)}")
    print(f"Refreshed the skills table in {README_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
